version: '3.4'

volumes:
  postgresql:
services:
  web:
    build: .
    volumes:
      - .:/app
    ports:
      - 8000:8000
    stdin_open: true
    tty: true
    depends_on:
      - db
  db:
    image: postgres:12
    ports:
      - 5432:5432
    volumes:
      - postgresql:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: 'ggh_booking'
      POSTGRES_USER: 'ggh_booking'
      POSTGRES_PASSWORD: 'admin'